databases:
  - name: bourse-db
    plan: free

redis:
  - name: bourse-redis
    plan: free

envVarGroups:
  - name: bourse-shared-env
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bourse-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: bourse-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: FINNHUB_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ALLOWED_HOSTS
        value: bourse-app.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://bourse-app.onrender.com

services:
  # 1. Web Service (Django + Daphne pour WebSockets)
  - type: web
    name: bourse-app
    plan: starter
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    preDeployCommand: "python manage.py migrate"
    startCommand: daphne -b 0.0.0.0 -p $PORT config.asgi:application
    healthCheckPath: /
    envVars:
      - fromGroup: bourse-shared-env

  # 2. Celery Worker (Traitement des tâches)
  - type: worker
    name: bourse-worker
    plan: starter
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker --loglevel=info"
    envVars:
      - fromGroup: bourse-shared-env

  # 3. Celery Beat (Planificateur de tâches)
  - type: worker
    name: bourse-beat
    plan: starter
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config beat --loglevel=info"
    envVars:
      - fromGroup: bourse-shared-env

  # 4. Flux Finnhub (Tâche longue durée)
  - type: worker
    name: bourse-flux-websocket
    plan: starter
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A config worker --loglevel=info -Q finnhub_flux" # Worker dédié pour les tâches du flux Finnhub
    envVars:
      - fromGroup: bourse-shared-env