# Generated by Django 4.2.29 on 2026-03-21 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('place_bourse', models.CharField(default='NASDAQ', max_length=20)),
                ('devise', models.CharField(default='USD', max_length=3)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
                'ordering': ['symbole'],
            },
        ),
        migrations.CreateModel(
            name='Portefeuille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('solde_cash', models.DecimalField(decimal_places=2, default=10000, max_digits=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portefeuilles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50)),
                ('telegram_actif', models.BooleanField(default=False)),
                ('devise_affichage', models.CharField(default='USD', max_length=3)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_op', models.CharField(choices=[('ACHAT', 'Achat'), ('VENTE', 'Vente')], max_length=5)),
                ('quantite', models.DecimalField(decimal_places=4, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=4, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourse.action')),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bourse.portefeuille')),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('PRIX_HAUT', 'Prix ≥ seuil'), ('PRIX_BAS', 'Prix ≤ seuil'), ('RSI_HAUT', 'RSI > 70'), ('RSI_BAS', 'RSI < 30'), ('MACD', 'Croisement MACD')], default='PRIX_HAUT', max_length=20)),
                ('seuil', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notif_telegram', models.BooleanField(default=True)),
                ('notif_email', models.BooleanField(default=False)),
                ('desactiver_apres', models.BooleanField(default=True)),
                ('message_perso', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_declenchement', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourse.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_detenue', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('prix_moyen_achat', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('valeur_actuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('plus_moins_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bourse.action')),
                ('portefeuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='bourse.portefeuille')),
            ],
            options={
                'verbose_name': 'Position',
                'unique_together': {('portefeuille', 'action')},
            },
        ),
        migrations.CreateModel(
            name='IndicateurCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rsi_14', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('macd', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('macd_signal', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('macd_hist', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('bollinger_haut', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('bollinger_bas', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('bollinger_mid', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('sma_20', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('sma_50', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('ema_50', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('atr', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('mis_a_jour', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicateurs', to='bourse.action')),
            ],
            options={
                'verbose_name': 'Indicateur (cache)',
                'ordering': ['-date'],
                'unique_together': {('action', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DonneeHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ouverture', models.DecimalField(decimal_places=4, max_digits=12)),
                ('plus_haut', models.DecimalField(decimal_places=4, max_digits=12)),
                ('plus_bas', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cloture', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('cloture_ajustee', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='bourse.action')),
            ],
            options={
                'verbose_name': 'Donnée historique',
                'ordering': ['-date'],
                'unique_together': {('action', 'date')},
            },
        ),
    ]
