# Generated by Django 4.2.29 on 2026-03-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicateurcache',
            name='obv',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='indicateurcache',
            name='stoch_d',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='indicateurcache',
            name='stoch_k',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_pref',
            field=models.CharField(choices=[('dark', 'Sombre'), ('light', 'Clair')], default='dark', max_length=10),
        ),
    ]
